In [1]:
import torch

In [2]:
print(torch.__version__)

2.5.1+cu121


# 1. PyTorch fundamentals

## 1. Creating Tensors

In [4]:
#@title Scalar
scalar = torch.tensor(235)
print("scalar =", scalar)
print("scalar.ndim =", scalar.ndim)
print("scalar.shape =", scalar.shape)

scalar = tensor(235)
scalar.ndim = 0
scalar.shape = torch.Size([])


In [5]:
#@title Vector
vector = torch.tensor([1, 2, 3])
print("vector =", vector)
print("vector.ndim =", vector.ndim)
print("vector.shape =", vector.shape)

vector = tensor([1, 2, 3])
vector.ndim = 1
vector.shape = torch.Size([3])


Elementos de um tensor de dimensão 1 (vetor) podem ser acessados usando somente um índice (exemplo abaixo).

In [6]:
for i in range(vector.shape[0]):
    print(f"vector[{i}] =", vector[i])

vector[0] = tensor(1)
vector[1] = tensor(2)
vector[2] = tensor(3)


Como é armazenado em memória

In [7]:
print("vector.dtype =", vector.dtype)

vector.dtype = torch.int64


In [8]:
#@title Matrix
MATRIX = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
print("MATRIX =", MATRIX)
print("MATRIX.ndim =", MATRIX.ndim)
print("MATRIX.shape =", MATRIX.shape)
print("MATRIX.dtype =", MATRIX.dtype)

MATRIX = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
MATRIX.ndim = 2
MATRIX.shape = torch.Size([3, 3])
MATRIX.dtype = torch.int64


Tensor de dimensão 2 precisa de índices para acessar todos os elementos.

- Primeiro índice = Linha
- Segundo índice = Coluna

In [9]:
for i in range(MATRIX.shape[0]):
    print(f"MATRIX[{i}] =", MATRIX[i])
    for j in range(MATRIX.shape[1]):
        print(f"MATRIX[{i}, {j}] =", MATRIX[i, j])

MATRIX[0] = tensor([1, 2, 3])
MATRIX[0, 0] = tensor(1)
MATRIX[0, 1] = tensor(2)
MATRIX[0, 2] = tensor(3)
MATRIX[1] = tensor([4, 5, 6])
MATRIX[1, 0] = tensor(4)
MATRIX[1, 1] = tensor(5)
MATRIX[1, 2] = tensor(6)
MATRIX[2] = tensor([7, 8, 9])
MATRIX[2, 0] = tensor(7)
MATRIX[2, 1] = tensor(8)
MATRIX[2, 2] = tensor(9)


In [10]:
#@title Tensor
M1 = [[1,2,3],
     [4,5,6],
     [7,8,9]]
M2 = [[10,11,12],
     [13,14,15],
     [16,17,18]]
TENSOR = torch.tensor([M1, M2])
print("TENSOR =", TENSOR)
print("TENSOR.ndim =", TENSOR.ndim)
print("TENSOR.shape =", TENSOR.shape)
print("TENSOR.dtype =", TENSOR.dtype)

TENSOR = tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
TENSOR.ndim = 3
TENSOR.shape = torch.Size([2, 3, 3])
TENSOR.dtype = torch.int64


In [11]:
for i in range(TENSOR.shape[0]):
  for j in range(TENSOR.shape[1]):
    for k in range(TENSOR.shape[2]):
      print(f"TENSOR[{i}, {j}, {k}] =", TENSOR[i, j, k])

TENSOR[0, 0, 0] = tensor(1)
TENSOR[0, 0, 1] = tensor(2)
TENSOR[0, 0, 2] = tensor(3)
TENSOR[0, 1, 0] = tensor(4)
TENSOR[0, 1, 1] = tensor(5)
TENSOR[0, 1, 2] = tensor(6)
TENSOR[0, 2, 0] = tensor(7)
TENSOR[0, 2, 1] = tensor(8)
TENSOR[0, 2, 2] = tensor(9)
TENSOR[1, 0, 0] = tensor(10)
TENSOR[1, 0, 1] = tensor(11)
TENSOR[1, 0, 2] = tensor(12)
TENSOR[1, 1, 0] = tensor(13)
TENSOR[1, 1, 1] = tensor(14)
TENSOR[1, 1, 2] = tensor(15)
TENSOR[1, 2, 0] = tensor(16)
TENSOR[1, 2, 1] = tensor(17)
TENSOR[1, 2, 2] = tensor(18)


## 2. Generating Tensors

### Random

In [12]:
R = torch.rand(4, 2, 5)
print("R =", R)
print("R.ndim =", R.ndim)
print("R.shape =", R.shape)
print("len(R) =", len(R))
print("R.numel() =", R.numel()) # 4 * 2 * 5 = 40
print("R.dtype =", R.dtype)

R = tensor([[[0.5913, 0.0339, 0.4911, 0.8937, 0.6908],
         [0.4982, 0.4180, 0.1819, 0.5678, 0.7380]],

        [[0.0394, 0.6854, 0.5174, 0.2999, 0.1114],
         [0.5024, 0.0523, 0.0110, 0.8569, 0.8986]],

        [[0.3761, 0.9958, 0.8654, 0.8049, 0.1656],
         [0.2059, 0.0427, 0.7333, 0.1295, 0.2520]],

        [[0.2803, 0.2421, 0.1514, 0.5144, 0.3184],
         [0.1845, 0.8346, 0.4606, 0.5643, 0.3639]]])
R.ndim = 3
R.shape = torch.Size([4, 2, 5])
len(R) = 4
R.numel() = 40
R.dtype = torch.float32


### Zeros & Ones

In [13]:
R = torch.zeros(4, 2, 5)
print("R =", R)
print("R.dtype =", R.dtype)

R = tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
R.dtype = torch.float32


In [14]:
R = torch.ones(4, 2, 5)
print("R =", R)
print("R.dtype =", R.dtype)

R = tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
R.dtype = torch.float32


### Range

In [15]:
print(torch.arange(0, 10))
print(torch.arange(0, 10, 2))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])


### Tensor Like

In [16]:
T1 = torch.rand(2, 2, 2)
print(T1)
print("T1.shape =", T1.shape)
T2 = torch.zeros_like(T1)
print(T2)
print("T2.shape =", T2.shape)

tensor([[[0.4347, 0.3871],
         [0.8004, 0.5652]],

        [[0.7678, 0.1059],
         [0.7015, 0.4481]]])
T1.shape = torch.Size([2, 2, 2])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
T2.shape = torch.Size([2, 2, 2])


## 1.3 Tensors attributes

In [17]:
t = torch.tensor([3., 6., 9.],
                 dtype=torch.float16,
                 device="cpu",
                 requires_grad=False)
print("t =", t)
print("t.dtype =", t.dtype)
print("t.device =", t.device)
print("t.requires_grad =", t.requires_grad)

t = tensor([3., 6., 9.], dtype=torch.float16)
t.dtype = torch.float16
t.device = cpu
t.requires_grad = False


## 4. Tensor Operations

- Element-wise (add, sub, mult, div)
- Scalar (shift, scale)
- Matrix Product
- Produto escalar

In [18]:
T1 = torch.rand(2, 2)
T2 = torch.rand(2, 2)
print("T1 =", T1)
print("T2 =", T2)

# Element wise
print("T1 + T2 =", T1 + T2)
print("T1 - T2 =", T1 - T2)
print("T1 * T2 =", T1 * T2)
print("T1 / T2 =", T1 / T2)

T1 = tensor([[0.2017, 0.1979],
        [0.7128, 0.9513]])
T2 = tensor([[0.9820, 0.1183],
        [0.8466, 0.5277]])
T1 + T2 = tensor([[1.1837, 0.3162],
        [1.5595, 1.4791]])
T1 - T2 = tensor([[-0.7803,  0.0795],
        [-0.1338,  0.4236]])
T1 * T2 = tensor([[0.1981, 0.0234],
        [0.6035, 0.5021]])
T1 / T2 = tensor([[0.2054, 1.6721],
        [0.8420, 1.8026]])


In [19]:
# Scalar prod and shift
print("a * T1 =", 4. * T1)
print("a + T1 =", 10. + T1)

a * T1 = tensor([[0.8068, 0.7914],
        [2.8514, 3.8053]])
a + T1 = tensor([[10.2017, 10.1979],
        [10.7128, 10.9513]])


In [20]:
# Matrix prod
print("T1 @ T2 =", torch.matmul(T1, T2))
print("T1 @ T2 =", T1 @ T2)

T1 @ T2 = tensor([[0.3656, 0.1283],
        [1.5054, 0.5864]])
T1 @ T2 = tensor([[0.3656, 0.1283],
        [1.5054, 0.5864]])


In [21]:
# Dot prod
T1 = torch.rand(3)
T2 = torch.rand(3)
print("T1 =", T1)
print("T2 =", T2)
print("T1 @ T2 =", T1 @ T2)

T1 = tensor([0.1682, 0.0327, 0.8280])
T2 = tensor([0.5985, 0.1234, 0.1211])
T1 @ T2 = tensor(0.2050)


### Torch matmul is fast

In [4]:
def matmul(A, B):
  # A(m x n) * B (p x q) = C(m x q), se n == p
  m = len(A)
  n = len(A[0])
  p = len(B)
  q = len(B[0])
  assert n == p, "n != p"

  C = [[0 for _ in range(q)] for _ in range(m)] # (m x q)

  for i in range(m):
    for j in range(q):
      for k in range(n):
        C[i][j] += A[i][k] * B[k][j]
  return C

In [43]:
A = torch.rand(50, 50)
B = torch.rand(50, 50)
C1 = torch.tensor(matmul(A, B))
C2 = torch.matmul(A, B)
print("Equal?", torch.all(C1 - C2 < 1e-05))

Equal? tensor(True)


In [44]:
%%time
C1 = matmul(A, B)

CPU times: user 3.18 s, sys: 22.8 ms, total: 3.2 s
Wall time: 3.28 s


In [45]:
%%time
C2 = A @ B

CPU times: user 122 µs, sys: 3 µs, total: 125 µs
Wall time: 132 µs


## 5. Tensor Aggregation



In [48]:
x = torch.arange(0, 100, 10, dtype = torch.float32)
print("x =", x)
print("x.min() =", x.min())
print("x.max() =", torch.max(x))

x = tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])
x.min() = tensor(0.)
x.max() = tensor(90.)
x.mean() = tensor(45.)


In [54]:
X = torch.rand(5, 3)
print("X =", X)
print("X.mean() =", X.mean())
print("X.mean(axis=0) =", X.mean(axis=0)) # Column-wise
print("X.mean(axis=1) =", X.mean(axis=1)) # Row-wise

X = tensor([[0.4883, 0.9520, 0.5526],
        [0.1990, 0.4888, 0.1579],
        [0.9221, 0.8559, 0.3942],
        [0.9103, 0.6662, 0.6777],
        [0.8039, 0.7190, 0.6191]])
X.mean() = tensor(0.6271)
X.mean(axis=0) = tensor([0.6647, 0.7364, 0.4803])
X.mean(axis=1) = tensor([0.6643, 0.2819, 0.7241, 0.7514, 0.7140])


In [58]:
x = torch.rand(5, 1)
print(f"x.T = {x.T}")
print(f"Max of x: {x.max()} at index = {x.argmax()}")

x.T = tensor([[0.0831, 0.8276, 0.3075, 0.0583, 0.4471]])
Max of x: 0.8276044726371765 at index = 1


## 6. Reshapes

In [64]:
# Remember big TENSOR
TENSOR, TENSOR.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [67]:
# One liner using reshape
x = torch.arange(1, 19).reshape(2, 3, 3)
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [70]:
# View vs. reshape
y = x.reshape(1, 18)
z = x.view(1, 18)
x[0, 1, 1] = 100
print("x =", x)
print("y =", y)
print("z =", z)

x = tensor([[[  1,   2,   3],
         [  4, 100,   6],
         [  7,   8,   9]],

        [[ 10,  11,  12],
         [ 13,  14,  15],
         [ 16,  17,  18]]])
y = tensor([[  1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11,  12,  13,  14,
          15,  16,  17,  18]])
z = tensor([[  1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11,  12,  13,  14,
          15,  16,  17,  18]])


In [84]:
# stack vs. vstack vs. hstack
X = torch.rand(2, 2)
print(torch.stack([X, X, X], axis = 0))
print()
print(torch.stack([X, X, X], axis = 1))
print()
print(torch.stack([X, X, X], axis = 2))

tensor([[[0.2300, 0.7818],
         [0.0373, 0.7048]],

        [[0.2300, 0.7818],
         [0.0373, 0.7048]],

        [[0.2300, 0.7818],
         [0.0373, 0.7048]]])

tensor([[[0.2300, 0.7818],
         [0.2300, 0.7818],
         [0.2300, 0.7818]],

        [[0.0373, 0.7048],
         [0.0373, 0.7048],
         [0.0373, 0.7048]]])

tensor([[[0.2300, 0.2300, 0.2300],
         [0.7818, 0.7818, 0.7818]],

        [[0.0373, 0.0373, 0.0373],
         [0.7048, 0.7048, 0.7048]]])


In [90]:
print(torch.rand(10, 1))
print(torch.rand(10, 1).squeeze())
print(torch.rand(1, 10).squeeze().unsqueeze(dim = 1))

tensor([[0.8370],
        [0.3765],
        [0.1332],
        [0.7901],
        [0.8443],
        [0.3590],
        [0.2736],
        [0.0716],
        [0.2017],
        [0.8036]])
tensor([0.9448, 0.5254, 0.8436, 0.3839, 0.4192, 0.8904, 0.4012, 0.5753, 0.2385,
        0.6749])
tensor([[0.7364],
        [0.0445],
        [0.1923],
        [0.4901],
        [0.9933],
        [0.5501],
        [0.9588],
        [0.7888],
        [0.1970],
        [0.0693]])


## 7. Indexing

Semelhante a numpy...

## 8. Device GPU

In [1]:
# Iniciar um ambiente com gpu e rodar a partir daqui

In [96]:
import torch
import time
!nvidia-smi

Tue Dec 17 00:55:30 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P0              28W /  70W |    161MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [97]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [98]:
A = torch.rand(100, 100)
B = torch.rand(100, 100)
Agpu = A.to(device)
Bgpu = B.to(device)
Cmanual = torch.tensor(matmul(A, B))
Ctorch = torch.matmul(A, B)
Cgpu = torch.matmul(Agpu, Bgpu)
print("Equal (manual and torch)?", torch.all(Cmanual - Ctorch < 1e-05))
print("Equal (torch and gpu)?", torch.all(Ctorch - Cgpu.to("cpu") < 1e-05))

Equal (manual and torch)? tensor(False)
Equal (torch and gpu)? tensor(False)


In [99]:
t = time.perf_counter()
for _ in range(1):
  ctorch = matmul(
      torch.rand(100, 100),
      torch.rand(100, 100))
print(f"{time.perf_counter() - t:.3f} s")

12.595 s


In [100]:
t = time.perf_counter()
for _ in range(100):
  ctorch = torch.matmul(
      torch.rand(1024, 1024),
      torch.rand(1024, 1024))
print(f"{time.perf_counter() - t:.3f} s")

3.853 s


In [101]:
t = time.perf_counter()
for _ in range(100):
  cgpu = torch.matmul(
      torch.rand(1024, 1024).to(device),
      torch.rand(1024, 1024).to(device))
print(f"{time.perf_counter() - t:.3f} s")

1.416 s
